server:
  port: 8081
  #  servlet-path: /xqAppServer
  context-path: /xqAppServer
spring:
  application:
    name: xqAppServer
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
  thymeleaf:
    cache: false
    enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.18.100.173:3306/xqapp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: xqapp
    password: xqapp
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level: debug
mybatis:
  mapper-locations: classpath:mappers/**.xml
  type-aliases-package: com.jx.modules